### PR TITLE
Added uncrustify to coding style

### PR DESCRIPTION
**Pull request by sheiny**
Added uncrustify.cfg to coding style.
Use command "uncrustify -c uncrustify.cfg file.cpp" to generate file following the project coding style.
You may have to install the uncrustify package.

### CODE REVIEW

**Comment by csguth** [comment]
Could you apply this config in some piece of code and show us a screenshot?

**Comment by sheiny** [comment]
yes of course, sorry i made a mistake and sent .gitignore as the uncrustify.cfg
well i got the dot cfg from http://uncrustify.sourceforge.net/default.cfg
The only thing i modified was the line:

# Whether the 'class' body is indented
indent_class                              = false    # false/true

to 

# Whether the 'class' body is indented
indent_class                              = true    # false/true

As you can see the dot cfg is fully customizable we can adopt our own custom configuration.

I applied the dot cfg to all files in entity system and the tests still passing so i guess everything is fine.

here go few examples:
on the left the actual ophidian files on right the "uncrustified" files:
screenshot from 2016-09-17 13 02 27
screenshot from 2016-09-17 13 05 06

**Review by csguth — APPROVED** [review]

**Comment by csguth** [comment]
@sheiny, please update this branch, merging development into it. Then, I'll accept your PR.

**Comment by sheiny** [comment]
@csguth updated, can you check again?

**Pull request merged**
